version: '3.5'

services:

  node:
    container_name: plainly_ui
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      - NODE_ENV=development
    command: npm run dev
